Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Post/",include("PostApp.urls",namespace='PostApp')),
    path("",include("About_Contect.urls",namespace="About_Contect")),
    path("account/",include("account.urls",namespace="Account")),
    path("Comment/",include("Comments.urls",namespace="Comment")),
    path("password/",include("Password_Forget.urls",namespace="Password")),
    # path("password_reset/", auth_views.PasswordResetView.as_view(template_name='password/password_reset.html',
    #                                                             html_email_template_name='password/password_reset_email.html'),
    #      name="password_reset"),
    # path('password_reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
    #      name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Comments/urls.py
from django.urls import path
from . import views
app_name = 'Comment'

urlpatterns = [
    path("CommentUpdate/<id>",views.CommentUpdate,name="CommentUpdate"),
    path("CommentDelete/<id>",views.CommentDelete,name="CommentDelete"),
]

PostApp/urls.py
from django.urls import path
from . import views
app_name = 'PostApp'

urlpatterns = [
    path("show/",views.ShowPost,name="show"),
    path("UserPost/",views.UserPost,name="UserPost"),
    path("detail/<id>",views.PostDetail,name='PostDetail'),
    path("CreatePost/",views.CreatePost,name="CreatePost"),
    path("update/<id>",views.UpdatePost,name="UpdatePost"),
    path("delete/<id>",views.DeletePost,name="DeletePost"),
    path("add_fav/<id>",views.add_fav,name="add_fav"),
    path("ShowLike",views.ShowLike,name="ShowLike"),

]

templates/Post/blog.html
{% extends "base.html" %}
{% block title %}Post | Blog{% endblock %}
{% block content %}
<div class="small-container">
    <h2 class="title">Blog Posts</h2>
    <div class="row">
        {% for post in All_Post %}
        <div class="col-4">
            {% if post.image %}
            <a href="{% url 'PostApp:PostDetail' post.id %}"><img src="{{ post.image.url }}"></a>
            {% endif %}
            <h4>{{post.title}}</h4>
            <p>{{post.body|slice:":50"}}</p>
            <div class="read-more">
                <a href="{% url 'PostApp:PostDetail' post.id %}" class="btn">Read More</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pageclass">
        {% if All_Post.has_other_pages %}
            {% if All_Post.has_previous %}
            <a href="?page={{All_Post.previous_page_number}}"><span>&#x2190;</span></a>
            {% else %}
              <a href=""><span>&#x2190;</span></a>
            {% endif %}
                {% for i in All_Post.paginator.page_range %}
                {% if All_Post.number == i %}
                <a href=""><span>{{i}}</span></a>
                {% else %}
                <a href="?page={{i}}"><span>{{i}}</span></a>
                {% endif %}
                {% endfor %}
            {% if All_Post.has_next %}
            <a href="?page={{All_Post.next_page_number}}"><span>&#8594;</span></a>
            {% else %}
            <a href=""><span>&#8594;</span></a>
            {% endif %}
        {% endif %}
    </div>

</div>
{% endblock %}

templates/Post/create.html
{% extends "base.html" %}
{% block title %}Create-Post | Blog{% endblock %}
{% block content %}


<div class="header">
    <div class="container">
        <div class="contect-page">
            <div class="row">
                <div class="form">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="title">Post Title</label>
                        <input type="text" name="title" required>
                        <label for="body">Post Body</label>
                        <textarea cols="30" rows="10" name="body" required></textarea>
                        <label for="Post Image">Image</label>
                        <input type="file" accept="image/*" name="image" style="border: none;padding: 0;" required>
                        <button type="submit" class="batton">create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/Post/delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}Delete-Post | Blog{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-2">
            <img src="{% static 'images/delete.jpg' %}" alt="">
        </div>
        <div class="col-2">
            <form method="POST">
                {% csrf_token %}
                <h2>are you sure to delete post?</h2>
                <br>
                <br>
                <a href="{% url 'PostApp:show' %}" class="delete-form">cancel</a>
                <a href=""><button type="submit" class="delete-form">Delete</button></a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/Post/detail.html
{% extends "base.html" %}
{% block title %}Detail | Blog{% endblock %}
{% block content %}
<div class="container">
    <div class="small-container single-post">
        <div class="row">
            <div class="col-2">
                <img src="{{postdetail.image.url}}" height="500px" width="500px">
            </div>
            <div class="col-2">
                {% if fav %}
                <a href="{% url 'PostApp:ShowLike' %}" class="btn">Remove Favourties</a>
                {% else %}
                <a href="{% url 'PostApp:add_fav' postdetail.id %}" class="btn">Add to Favourties</a>
                {% endif %}
                <h3>Post Name</h3>
                <p>{{postdetail.title}}</p>
                <br>
                <h3>Blog Details</h3>
                <p>{{postdetail.body}}</p>
                <br>
                <h3>Author</h3>
                <p>{{postdetail.author.name}}</p>
                <br>
                <h3>Created</h3>
                <p>{{postdetail.created}}</p>
                {% if user.id == postdetail.author.id %}
                <a href="{% url 'PostApp:UpdatePost' postdetail.id %}"><button type="submit"
                        class="btn">Update</button></a>
                <a href="{% url 'PostApp:DeletePost' postdetail.id %}"><button type="submit"
                        class="btn">Delete</button></a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="small-container">
        <h2 class="title">Related Posts</h2>
        <div class="row">
            {% for post in relatedpost %}
            <div class="col-4">
                {% if post.image %}
                <a href="{% url 'PostApp:PostDetail' post.id %}"><img src="{{ post.image.url }}"></a>
                {% endif %}
                <h4>{{post.title}}</h4>
                <p>{{post.body|slice:":50"}}</p>
                <div class="read-more">
                    <a href="{% url 'PostApp:PostDetail' post.id %}" class="btn">Read More</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <h2>Add comment</h2>
            <div class="row allcomments">
                {% for c in postdetail.comment.all %}
                <div class="comments">
                    <img src="{{c.image.url}}">
                    <div class="comments-detail">
                        <h3>{{c.name}}</h3>
                        <p>{{c.message}}
                        </p>
                        <div class="commentdate">
                            {% if user.id == c.author.id %}
                            <a href="{% url 'Comment:CommentUpdate' c.id %}"><button type="submit"
                                    class="commentbtn">Update</button></a>&nbsp;&nbsp;
                            <a href="{% url 'Comment:CommentDelete' c.id %}"><button type="submit"
                                    class="commentbtn">Delete</button></a>
                            {% endif %}
                            <p class="date"> {{c.created}} </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="form">
            <h2>leave a comment</h2>
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                <label for="Email">Name</label>
                <input type="text" name="name" required>
                <label for="Message">Message</label>
                <textarea cols="30" rows="10" name="message" required></textarea>
                <button type="submit" class="batton">Send Message</button>
            </form>
        </div>


    </div>
</div>

{% endblock %}

templates/Post/home.html
{% extends "base.html" %}
{% block title %}Home | Blog{% endblock %}
{% block content %}
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <h1>Workout<br>A new Style</h1>
                <p>Lorem Ipsum has been the industry's standard dummy text ever since <br> the 1500s, when an
                    unknown printer took a galley of type and scrambled it to make a</p>
                <a href="{% url 'PostApp:show' %}" class="btn">Explore Now &#8594;</a>
            </div>
        </div>
    </div>
</div>


<div class="small-container">
    <h2 class="title">Letest Posts</h2>
    <div class="row">
        {% for post in LetestPost %}
        <div class="col-4">
            {% if post.image %}
            <a href="{% url 'PostApp:PostDetail' post.id %}"><img src="{{ post.image.url }}"></a>
            {% endif %}
            <h4>{{post.title}}</h4>
            <p>{{post.body|slice:":50"}}</p>
            <div class="read-more">
                <a href="{% url 'PostApp:PostDetail' post.id %}" class="btn">Read More</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/Post/showprofile.html
{% extends "base.html" %}
{% block title %}Post | Blog{% endblock %}
{% block content %}


<div class="container">
    <div class="col-2">
        <div class="row">
            <div class="col-2">
                <br>
                <h2>Commented Post List</h2>
                <br>
                <div class="allcommentpost">
                    {% for i in com %}
                    {% if blog.email == i.author.email %}
                    <div class="profile">
                        <h4>Post Name : </h4>&nbsp;&nbsp;
                        <p><a href="{% url 'PostApp:PostDetail' i.post.id %}">{{i.post.title}}</a></p>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="col-2">
                <br>
                <h2>Likes Post List</h2>
                <br>
                <div class="alllikepost">
                    {% for i in new %}
                    <div class="profile">
                        <h4>Post Name : </h4>&nbsp;&nbsp;
                        <p><a href="{% url 'PostApp:PostDetail' i.id %}">{{i.title}}</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'PostApp:add_fav' i.id %}" class="likeremovebtn">Remove</a>
                        </p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/Post/update.html
{% extends "base.html" %}
{% block title %}Update-Post | Blog{% endblock %}
{% block content %}
    <div class="container">
        <div class="small-container single-post">
            <div class="row">
                <div class="col-2">
                    <img src="{{blog.image.url}}" height="500px" width="500px">
                    
                </div>
                <div class="col-2">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="title">Post Title</label>
                        <input type="text" value="{{blog.title}}" name="title">
                        <label for="body">Post Body</label>
                        <textarea cols="30" rows="10" name="body">{{blog.body}}</textarea>
                        <label for="Post Image">Image</label>
                        <input type="file" accept="image/*" name="image" style="border: none;padding: 0;">
                        <button type="submit" class="batton">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Post/user_post.html
{% extends "base.html" %}
{% block title %}User-Posts | Blog{% endblock %}
{% block content %}

<div class="small-container">
    <h2 class="title">{{request.user.name}} Posts</h2>
    <div class="row">
        {% for post in All_Post %}
        <div class="col-4">
            {% if post.image %}
            <a href="{% url 'PostApp:PostDetail' post.id %}"><img src="{{ post.image.url }}"></a>
            {% endif %}
            <h4>{{post.title}}</h4>
            <p>{{post.body|slice:":50"}}</p>
            <div class="read-more">
                <a href="{% url 'PostApp:PostDetail' post.id %}" class="btn">Read More</a>
            </div>
        </div>
        {% endfor %}
    </div>

<div class="pageclass">
    {% if All_Post.has_other_pages %}
        {% if All_Post.has_previous %}
        <a href="?page={{All_Post.previous_page_number}}"><span>&#x2190;</span></a>
        {% else %}
          <a href=""><span>&#x2190;</span></a>
        {% endif %}
            {% for i in All_Post.paginator.page_range %}
            {% if All_Post.number == i %}
            <a href=""><span>{{i}}</span></a>
            {% else %}
            <a href="?page={{i}}"><span>{{i}}</span></a>
            {% endif %}
            {% endfor %}
        {% if All_Post.has_next %}
        <a href="?page={{All_Post.next_page_number}}"><span>&#8594;</span></a>
        {% else %}
        <a href=""><span>&#8594;</span></a>
        {% endif %}
    {% endif %}
</div>
</div>
{% endblock %}